version: '3.9'

services:

  parser_avito:
    restart: always
    build:
      target: production
    ports:
      - 8090:8080
    command: npm run start

  parser_domclick:
    restart: always
    build:
      target: production
    ports:
      - 8091:8080
    command: npm run start

  parser_cian:
    restart: always
    build:
      target: production
    ports:
      - 8092:8080
    command: npm run start

  parser_sibdom:
    restart: always
    build:
      target: production
    ports:
      - 8093:8080
    command: npm run start

  web_app:
    restart: always
    build:
      target: production
    environment:
      - NODE_ENV=production
    ports:
      - 80:8080
    command: npm run start

  get_data_api:
    restart: always
    build:
      target: production
    ports:
      - 8095:8080
    command: npm run start