version: '3.9'

services:

  parser_avito:
    image: parser_avito
    build:
      context: .
      dockerfile: ./parser_avito/Dockerfile
      target: base
    environment:
      - MONGODB_CONNSTRING=mongodb://mongodb:27017/uni_parse
      - MONGODB_USERNAME=MongoUser
      - MONGODB_PASSWORD=Parasenok225
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=8080
      - NUM_RETRIES=3
    volumes:
      - ./parser_avito/src:/home/node/app/src
      - ./parser_avito/nodemon.json:/home/node/app/nodemon.json
      - chrome-data-volume-avito:/home/node/app/.config/google-chrome
    ports:
      - 8090:8080
    command: npm run dev

  parser_domclick:
    image: parser_domclick
    build:
      context: .
      dockerfile: ./parser_domclick/Dockerfile
      target: base
    environment:
      - MONGODB_CONNSTRING=mongodb://mongodb:27017/uni_parse
      - MONGODB_USERNAME=MongoUser
      - MONGODB_PASSWORD=Parasenok225
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=8080
      - NUM_RETRIES=5
    volumes:
      - ./parser_domclick/src:/home/node/app/src
      - ./parser_domclick/nodemon.json:/home/node/app/nodemon.json
      - chrome-data-volume-domclick:/home/node/app/.config/google-chrome
    ports:
      - 8091:8080
    command: npm run dev

  parser_cian:
    image: parser_cian
    build:
      context: .
      dockerfile: ./parser_cian/Dockerfile
      target: base
    environment:
      - MONGODB_CONNSTRING=mongodb://mongodb:27017/uni_parse
      - MONGODB_USERNAME=MongoUser
      - MONGODB_PASSWORD=Parasenok225
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=8080
      - NUM_RETRIES=3
    volumes:
      - ./parser_cian/src:/home/node/app/src
      - ./parser_cian/nodemon.json:/home/node/app/nodemon.json
      - chrome-data-volume-cian:/home/node/app/.config/google-chrome
    ports:
      - 8092:8080
    command: npm run dev 
    
  parser_sibdom:
    image: parser_sibdom
    build:
      context: .
      dockerfile: ./parser_sibdom/Dockerfile
      target: base
    environment:
      - MONGODB_CONNSTRING=mongodb://mongodb:27017/uni_parse
      - MONGODB_USERNAME=MongoUser
      - MONGODB_PASSWORD=Parasenok225
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=8080
      - NUM_RETRIES=3
    volumes:
      - ./parser_sibdom/src:/home/node/app/src
      - ./parser_sibdom/nodemon.json:/home/node/app/nodemon.json
      - chrome-data-volume-sibdom:/home/node/app/.config/google-chrome
    ports:
      - 8093:8080
    command: npm run dev

  web_app:
    image: web_app
    build:
      context: .
      dockerfile: ./web_app/Dockerfile
      target: base
    environment:
      - NODE_ENV=development
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=8080
    volumes:
      - ./web_app/src:/home/node/app/src
      - ./web_app/public:/home/node/app/public
      - ./web_app/nodemon.json:/home/node/app/nodemon.json
    ports:
      - 8094:8080
    command: npm run dev 
    
  get_data_api:
    image: get_data_api
    build:
      context: .
      dockerfile: ./get_data_api/Dockerfile
      target: base
    environment:
      - MONGODB_CONNSTRING=mongodb://mongodb:27017/uni_parse
      - MONGODB_USERNAME=MongoUser
      - MONGODB_PASSWORD=Parasenok225
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=8080
    volumes:
      - ./get_data_api/src:/home/node/app/src
      - ./get_data_api/nodemon.json:/home/node/app/nodemon.json
    ports:
      - 8095:8080
    command: npm run dev     

  mongodb:
    container_name: uni-parse-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MongoUser
      - MONGO_INITDB_ROOT_PASSWORD=Parasenok225
    volumes:
      - mongodb-data-volume:/data/db
      - mongodb-config-volume:/data/configdb
    ports:
      - 27018:27017
    command: mongod --quiet --logpath /dev/null 
    
volumes:
  mongodb-data-volume:
    name: uni-parse-mongodb-data
  mongodb-config-volume:
    name: uni-parse-mongodb-config
  chrome-data-volume-avito:
    name: uni-parse-chrome-data-avito 
  chrome-data-volume-domclick:
    name: uni-parse-chrome-data-domclick
  chrome-data-volume-cian:
    name: uni-parse-chrome-data-cian
  chrome-data-volume-sibdom:
    name: uni-parse-chrome-data-sibdom 